/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addcomp.java
 *
 * Created on 4 Jul, 2013, 2:00:08 PM
 */
package project1;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class addcomp extends javax.swing.JInternalFrame {

    /** Creates new form addcomp */
    public addcomp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        compbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add Categary");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Add Catogary");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 100, 110, 30);
        getContentPane().add(compbox);
        compbox.setBounds(200, 100, 250, 30);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 160, 120, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 180, 0, 0);

        jLabel3.setText("Added Categary(s)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 50, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categaries" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(200, 50, 250, 30);

        setBounds(0, 0, 501, 321);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "insert into addcomp values(?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, compbox.getText());

                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Added successfully");
                mystatement.close();
                myconnection.close();
            } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException e) {
                JOptionPane.showMessageDialog(rootPane, "Category Already  added");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
                e.printStackTrace();
            }
        } catch (Exception e) {
            //jLabel1.setText("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());

        }

        compbox.setText(null);


    }//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    String path = "jdbc:mysql://localhost:3306/";
    String place = "project1";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection myconnection = DriverManager.getConnection(path + place, "root", "");
        try {
            String q = "select * from addcomp";
            PreparedStatement mystatement = myconnection.prepareStatement(q);
            ResultSet myresult = mystatement.executeQuery();
            if (myresult.next()) {
                do {
                    jComboBox1.addItem(myresult.getString("comapnyname"));
                } while (myresult.next());

            } else {
                jComboBox1.addItem("No Catogary added yet");
            }
            mystatement.close();
            myconnection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
    }


}//GEN-LAST:event_formInternalFrameOpened
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField compbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
