/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * createuser2.java
 *
 * Created on 2 Jul, 2013, 1:50:08 PM
 */
package project1;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class createuser2 extends javax.swing.JInternalFrame {

    /** Creates new form createuser2 */
    public createuser2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        passwordbox = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add Admin");
        getContentPane().setLayout(null);

        jLabel1.setText("UserName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 90, 30);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 74, 90, 30);
        getContentPane().add(userbox);
        userbox.setBounds(160, 30, 160, 30);
        getContentPane().add(passwordbox);
        passwordbox.setBounds(160, 80, 160, 30);

        jButton1.setText("Save ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 140, 110, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 330, 130, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 280, 0, 200);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-405)/2, (screenSize.height-253)/2, 405, 253);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "insert into usertable values(?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, userbox.getText());
                mystatement.setString(2, passwordbox.getText());
                mystatement.setString(3, "Admin");
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "saved successfully");
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //jLabel1.setText("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //jLabel1.setText("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());

        }
        userbox.setText(null);
        passwordbox.setText(null);


    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JTextField userbox;
    // End of variables declaration//GEN-END:variables
}
