/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newstock.java
 *
 * Created on 28 Jun, 2013, 7:07:40 PM
 */
package project1;

import java.sql.*;
import javax.swing.JOptionPane;

public class deleteiqbalstock extends javax.swing.JInternalFrame {

    /** Creates new form newstock */
    public deleteiqbalstock() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namebox1 = new javax.swing.JLabel();
        quantitybox1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        amountbox = new javax.swing.JTextField();
        quanbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clear Stock");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        namebox1.setText("Product Name");
        getContentPane().add(namebox1);
        namebox1.setBounds(20, 70, 120, 14);

        quantitybox1.setText("Quantity");
        getContentPane().add(quantitybox1);
        quantitybox1.setBounds(20, 230, 120, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 70, 170, 30);

        jLabel3.setText("Price Per Item");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 90, 14);

        jLabel2.setText("Product Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 120, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product Type" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(210, 120, 170, 30);

        amountbox.setEditable(false);
        getContentPane().add(amountbox);
        amountbox.setBounds(210, 170, 170, 30);

        quanbox.setEditable(false);
        getContentPane().add(quanbox);
        quanbox.setBounds(210, 230, 170, 30);

        jButton1.setText("Search by ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 20, 200, 30);

        jButton2.setText("Clear Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 300, 170, 40);

        jLabel1.setText("Stock ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 80, 14);
        getContentPane().add(num);
        num.setBounds(210, 20, 170, 30);

        jButton3.setText("Search acc to Product & Product Type");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 120, 260, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 340, 360, 0);

        setBounds(0, 0, 707, 417);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from addcomp";
                PreparedStatement mystatement = myconnection.prepareStatement(q);



                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {
                    do {
                        jComboBox1.addItem(myresult.getString("comapnyname"));
                    } while (myresult.next());

                } else {
                    jComboBox1.addItem("No Product added yet");
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }



    }//GEN-LAST:event_formInternalFrameActivated

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";

        if (jComboBox1.getSelectedIndex() != 0) {
            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");
                try {
                    String q = "select producttype from addstock where comapnyname=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, jComboBox1.getSelectedItem().toString());


                    ResultSet myresult = mystatement.executeQuery();
                    jComboBox2.removeAllItems();
                    if (myresult.next()) {
                        jComboBox2.addItem("Choose product");
                        do {
                            jComboBox2.addItem(myresult.getString("producttype"));
                        } while (myresult.next());
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "no producttype found");
                    }


                    mystatement.close();
                    myconnection.close();
                } catch (Exception e) {
                    //System.out.println("Error in query"+e.getMessage());
                    JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
                }
            } catch (Exception e) {
                //System.out.println("Error on connnection"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from newstock1 where no=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, num.getText());


                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {

                    String dob = myresult.getString("namebox");
                    //String a[]=dob.split("");
                    jComboBox1.setSelectedItem(dob);
                    String dob1 = myresult.getString("stocknamebox");
                    // String ab[]=dob1.split("");
                    jComboBox2.setSelectedItem(dob1);
                    amountbox.setText(myresult.getString("amountbox"));
                    quanbox.setText(myresult.getString("quantitybox"));

                } else {
                    JOptionPane.showMessageDialog(rootPane, "no product available");
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "update newstock1 set quantitybox='0' where namebox=? and stocknamebox=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, jComboBox1.getSelectedItem().toString());
                mystatement.setString(2, jComboBox2.getSelectedItem().toString());
                int b = mystatement.executeUpdate();
                if (b > 0) {

                    JOptionPane.showMessageDialog(rootPane, "Stock cleared Successfully");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Already Deleted");
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }
        amountbox.setText(null);
        // no.setText(null);
        quanbox.setText(null);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        num.setText(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from newstock1 where namebox=? and stocknamebox=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, jComboBox1.getSelectedItem().toString());
                mystatement.setString(2, jComboBox2.getSelectedItem().toString());


                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {
                    num.setText(myresult.getString("no"));
                    amountbox.setText(myresult.getString("amountbox"));
                    quanbox.setText(myresult.getString("quantitybox"));

                } else {
                    JOptionPane.showMessageDialog(rootPane, "no product available");
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel namebox1;
    private javax.swing.JTextField num;
    private javax.swing.JTextField quanbox;
    private javax.swing.JLabel quantitybox1;
    // End of variables declaration//GEN-END:variables
}
