/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * listofstock.java
 *
 * Created on 5 Jul, 2013, 9:46:42 PM
 */

package project1;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sony
 */
public class listofstock extends javax.swing.JInternalFrame {

    /** Creates new form listofstock */
    public listofstock() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("List Of Stock");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Category" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 20, 230, 30);

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Product", "Product Type", "Price", "Current Stock"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 770, 402);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 480, 140, 30);

        setBounds(0, 0, 868, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
       String path="jdbc:mysql://localhost:3306/";
        String place="project1";
         try
          {
         Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection=DriverManager.getConnection(path+place,"root","");
         try
          {
             String q="select * from addcomp";
             PreparedStatement mystatement=myconnection.prepareStatement(q);



             ResultSet myresult=mystatement.executeQuery();

             if(myresult.next())
             {
                do
                {
                    jComboBox1.addItem(myresult.getString("comapnyname"));
                }
                while(myresult.next());

             }
             else
             {
               jComboBox1.addItem("No product added yet");
             }


             mystatement.close();
             myconnection.close();
           }

         catch(Exception e)
          {
            //System.out.println("Error in query"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query"+e.getMessage());
          }
        }
        catch(Exception e)
        {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query"+e.getMessage());
    }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
          String path="jdbc:mysql://localhost:3306/";
        String place="project1";
         try
          {
         Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection=DriverManager.getConnection(path+place,"root","");

            String no,cname,pname,amount,quantity;
         try
          {
             String q="select * from newstock1 where namebox=?";
             PreparedStatement mystatement=myconnection.prepareStatement(q);
             mystatement.setString(1,jComboBox1.getSelectedItem().toString());

             DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();

             ResultSet myresult=mystatement.executeQuery();
             mymodel.setRowCount(0);
             if(myresult.next())
             {
               jTable1.setVisible(true);
               do
               {
                   no=myresult.getString("no");
                   cname=myresult.getString("namebox");
                   pname=myresult.getString("stocknamebox");
                   amount=myresult.getString("amountbox");
                   quantity=myresult.getString("quantitybox");
                   mymodel.addRow(new Object[]{no,cname,pname,amount,quantity});
               }
               while(myresult.next());
             }
             else
             {
                 jTable1.setVisible(false);
               JOptionPane.showMessageDialog(rootPane,"no records present");
             }


             mystatement.close();
             myconnection.close();
           }

         catch(Exception e)
          {
            //System.out.println("Error in query"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query"+e.getMessage());
          }
        }
        catch(Exception e)
        {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query"+e.getMessage());
    }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              MessageFormat headerFormat = new MessageFormat("List Of Stock");
              MessageFormat footerFormat = new MessageFormat("- {0} -");
              jTable1.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
            }
	catch (PrinterException pe)
	{
              System.err.println("Error printing: " + pe.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
