/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * listofemployee.java
 *
 * Created on 5 Jul, 2013, 10:23:05 PM
 */

package project1;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sony
 */
public class listofemployee extends javax.swing.JInternalFrame {

    /** Creates new form listofemployee */
    public listofemployee() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("List Of Employee");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Name", "Address", "Salary", "Contact No.", "Gender", "Date Of Birth"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 690, 402);

        jButton1.setText("Print List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 450, 170, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-731)/2, (screenSize.height-542)/2, 731, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        String path="jdbc:mysql://localhost:3306/";
        String place="project1";
         try
          {
         Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection=DriverManager.getConnection(path+place,"root","");

            String id,name,add,sal,phone,gender,dob;
         try
          {
             String q="select * from newemployee";
             PreparedStatement mystatement=myconnection.prepareStatement(q);

             DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();

             ResultSet myresult=mystatement.executeQuery();
             mymodel.setRowCount(0);
             if(myresult.next())
             {
               //jTable1.setVisible(true);
               do
               {
                   id=myresult.getString("username");
                   name=myresult.getString("name");
                   add=myresult.getString("address");
                   sal=myresult.getString("salary");
                   phone=myresult.getString("contact_no");
                   gender=myresult.getString("gender");
                   dob=myresult.getString("dob");
                   mymodel.addRow(new Object[]{id,name,add,sal,phone,gender,dob});
               }
               while(myresult.next());
             }
             else
             {
                // jTable1.setVisible(false);
               JOptionPane.showMessageDialog(rootPane,"no records present");
             }


             mystatement.close();
             myconnection.close();
           }

         catch(Exception e)
          {
            //System.out.println("Error in query"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query"+e.getMessage());
          }
        }
        catch(Exception e)
        {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query"+e.getMessage());
    }

    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
              MessageFormat headerFormat = new MessageFormat("List Of Employees");
              MessageFormat footerFormat = new MessageFormat("- {0} -");
              jTable1.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
            }
	catch (PrinterException pe)
	{
              System.err.println("Error printing: " + pe.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
