/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newemployee.java
 *
 * Created on 2 Jul, 2013, 2:23:41 PM
 */
package project1;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony
 */
public class newemployee extends javax.swing.JInternalFrame {

    /** Creates new form newemployee */
    public newemployee() {
        initComponents();



        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                jComboBox1.addItem("0" + a);
            } else {
                jComboBox1.addItem(String.valueOf(a));
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                jComboBox2.addItem("0" + a);
            } else {
                jComboBox2.addItem(String.valueOf(a));
            }
        }
        for (int a = 2013; a > 1960; a--) {
            jComboBox3.addItem(String.valueOf(a));
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ab = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        mb = new javax.swing.JRadioButton();
        fb = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        passwordbox = new javax.swing.JPasswordField();
        pb = new javax.swing.JFormattedTextField();
        sb = new javax.swing.JFormattedTextField();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add Employee Info");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 20);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 70, 30);
        getContentPane().add(nb);
        nb.setBounds(90, 10, 170, 30);

        jLabel4.setText("Contact No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 184, 70, 20);

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 240, 100, 20);

        jLabel6.setText("DOB");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 330, 80, 30);

        ab.setColumns(20);
        ab.setRows(5);
        jScrollPane1.setViewportView(ab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 60, 170, 96);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(550, 50, 0, 2);

        buttonGroup1.add(mb);
        mb.setText("Male");
        getContentPane().add(mb);
        mb.setBounds(90, 230, 80, 23);

        buttonGroup1.add(fb);
        fb.setText("Female");
        getContentPane().add(fb);
        fb.setBounds(170, 230, 80, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 320, 60, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(160, 320, 70, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(240, 320, 80, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 390, 140, 40);

        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 120, 20);

        jLabel1.setText("UserName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 20, 80, 20);

        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 70, 90, 20);
        getContentPane().add(userbox);
        userbox.setBounds(380, 10, 150, 30);
        getContentPane().add(passwordbox);
        passwordbox.setBounds(380, 60, 150, 30);

        try {
            pb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(pb);
        pb.setBounds(90, 180, 170, 30);

        sb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(sb);
        sb.setBounds(90, 270, 170, 30);

        setBounds(0, 0, 567, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {



                String q2 = "insert into usertable values(?,?,?)";
                PreparedStatement mystatement2 = myconnection.prepareStatement(q2);
                mystatement2.setString(1, userbox.getText());
                mystatement2.setString(2, passwordbox.getText());
                mystatement2.setString(3, "Employee");
                mystatement2.execute();

                mystatement2.close();




                String q = "insert into newemployee values(?,?,?,?,?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, userbox.getText());
                mystatement.setString(2, nb.getText());
                mystatement.setString(3, ab.getText());
                mystatement.setString(4, sb.getText());
                mystatement.setString(5, pb.getText());
                if (mb.isSelected()) {
                    mystatement.setString(6, "Male");
                } else if (fb.isSelected()) {
                    mystatement.setString(6, "Female");
                }
                String dob = jComboBox3.getSelectedItem() + "-" + jComboBox2.getSelectedItem() + "-" + jComboBox1.getSelectedItem();
                mystatement.setString(7, dob);

                java.util.Date obj = new java.util.Date();
                SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                String dateofreg = myformat.format(obj);
                mystatement.setString(8, dateofreg);

                mystatement.execute();



                JOptionPane.showMessageDialog(rootPane, "saved successfully");
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //jLabel1.setText("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //jLabel1.setText("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());

        }

        userbox.setText("");
        passwordbox.setText("");
        nb.setText(null);
        ab.setText(null);
        pb.setText(null);
        buttonGroup1.clearSelection();
        jComboBox3.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        sb.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fb;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton mb;
    private javax.swing.JTextField nb;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JFormattedTextField pb;
    private javax.swing.JFormattedTextField sb;
    private javax.swing.JTextField userbox;
    // End of variables declaration//GEN-END:variables
}
