/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalesByday.java
 *
 * Created on Sep 5, 2013, 4:03:21 PM
 */
package project1;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author gtb
 */
public class SalesByday extends javax.swing.JInternalFrame {

    /** Creates new form SalesByday */
    public SalesByday() {
        initComponents();

        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                jComboBox1.addItem("0" + a);
            } else {
                jComboBox1.addItem(String.valueOf(a));
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                jComboBox2.addItem("0" + a);
            } else {
                jComboBox2.addItem(String.valueOf(a));
            }
        }
        for (int a = 2013; a < 2030; a++) {
            jComboBox3.addItem(String.valueOf(a));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Sales By day");
        getContentPane().setLayout(null);

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 80, 130, 30);

        jLabel2.setText("Select Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 36, 110, 34);

        jLabel3.setText("Sales Made :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 90, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(100, 40, 60, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(170, 40, 70, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(250, 40, 80, 30);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 40, 70, 30);

        setBounds(0, 0, 478, 217);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String path = "jdbc:mysql://localhost:3306/";
    String place = "project1";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection myconnection = DriverManager.getConnection(path + place, "root", "");
        try {

            String q = "Select * from billing where dateofbill=?";
            PreparedStatement ps = myconnection.prepareStatement(q);
            String d = jComboBox3.getSelectedItem() + "-" + jComboBox2.getSelectedItem() + "-" + jComboBox1.getSelectedItem();
            ps.setString(1, d);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                double prc = 0;
                do {
                    prc += Double.parseDouble(rs.getString(6));
                } while (rs.next());
                jLabel1.setText("Rs. " + prc);
            } else {
                jLabel1.setText("Rs. 0.0");
                JOptionPane.showMessageDialog(rootPane, "No sales found!!!");
            }
            ps.close();
            myconnection.close();

        } catch (Exception e) {
            //System.out.println("Error in query"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }
    } catch (Exception e) {
        //System.out.println("Error on connnection"+e.getMessage());
        JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
    }


}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
