/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newemployee.java
 *
 * Created on 2 Jul, 2013, 2:23:41 PM
 */
package project1;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sony
 */
public class updaterecord extends javax.swing.JInternalFrame {

    /** Creates new form newemployee */
    public updaterecord() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ab = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        mb = new javax.swing.JRadioButton();
        fb = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        eb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        sb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Update Employee Info");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 110, 14);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 90, 14);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 120, 14);
        getContentPane().add(nb);
        nb.setBounds(150, 90, 160, 30);

        jLabel4.setText("Contact No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 260, 110, 14);

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 380, 80, 14);

        jLabel6.setText("DOB");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 420, 70, 14);

        ab.setColumns(20);
        ab.setRows(5);
        jScrollPane1.setViewportView(ab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 140, 166, 96);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(550, 50, 0, 2);

        buttonGroup1.add(mb);
        mb.setText("Male");
        getContentPane().add(mb);
        mb.setBounds(150, 370, 80, 23);

        buttonGroup1.add(fb);
        fb.setText("Female");
        getContentPane().add(fb);
        fb.setBounds(240, 370, 80, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 420, 60, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(230, 420, 70, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(320, 420, 80, 30);

        jButton1.setText("Search ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 40, 90, 30);
        getContentPane().add(eb);
        eb.setBounds(150, 40, 160, 30);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 480, 130, 30);

        jButton3.setText("Search ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 90, 90, 30);

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Address", "Contact No."
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(350, 140, 480, 260);

        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 320, 110, 14);
        getContentPane().add(sb);
        sb.setBounds(150, 310, 170, 30);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 120, 210, 230);
        getContentPane().add(cb);
        cb.setBounds(150, 260, 170, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 480, 130, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-850)/2, (screenSize.height-566)/2, 850, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from newemployee where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, eb.getText());


                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {
                    nb.setText(myresult.getString("name"));
                    ab.setText(myresult.getString("address"));
                    cb.setText(myresult.getString("contact_no"));
                    sb.setText(myresult.getString("salary"));
                    if (myresult.getString("gender").equals("Male")) {
                        mb.setSelected(true);
                    } else if (myresult.getString("gender").equals("Female")) {
                        fb.setSelected(true);
                    }

                    String dob = myresult.getString("dob");
                    String a[] = dob.split("-");
                    jComboBox1.setSelectedItem(a[2]);
                    jComboBox2.setSelectedItem(a[1]);
                    jComboBox3.setSelectedItem(a[0]);


                } else {
                    JOptionPane.showMessageDialog(rootPane, "incorrect memberid");
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                jComboBox1.addItem("0" + a);
            } else {
                jComboBox1.addItem(String.valueOf(a));
            }
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                jComboBox2.addItem("0" + a);
            } else {
                jComboBox2.addItem(String.valueOf(a));
            }
        }
        for (int a = 2013; a > 1960; a--) {
            jComboBox3.addItem(String.valueOf(a));
        }
        jScrollPane3.setVisible(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "update newemployee set name=?, address=?, contact_no=?, salary=? , gender=?, dob=? where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, nb.getText());
                mystatement.setString(2, ab.getText());
                mystatement.setString(3, cb.getText());
                mystatement.setString(4, sb.getText());

                if (mb.isSelected()) {
                    mystatement.setString(5, "Male");
                } else if (fb.isSelected()) {
                    mystatement.setString(5, "Female");
                }
                String dob = jComboBox3.getSelectedItem() + "-" + jComboBox2.getSelectedItem() + "-" + jComboBox1.getSelectedItem();
                mystatement.setString(6, dob);
                mystatement.setString(7, eb.getText());
                mystatement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Updated Successfully");
                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //jLabel1.setText("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //jLabel1.setText("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());

        }
        nb.setText(null);
        sb.setText(null);
        ab.setText(null);
        cb.setText(null);
        buttonGroup1.clearSelection();
        jComboBox3.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int myrow = jTable1.getSelectedRow();

        eb.setText(jTable1.getValueAt(myrow, 0).toString());
        jButton1ActionPerformed(null);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jScrollPane3.setVisible(true);
        eb.setText(null);
        sb.setText(null);
        ab.setText(null);
        cb.setText(null);
        buttonGroup1.clearSelection();
        jComboBox3.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        String path = "jdbc:mysql://localhost:3306/";
        String place = "project1";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");

            String id, name, add, phone;
            try {
                String q = "select * from newemployee where name like '%" + nb.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);

                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();

                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                if (myresult.next()) {
                    //jTable1.setVisible(true);
                    do {
                        id = myresult.getString("username");
                        name = myresult.getString("name");
                        add = myresult.getString("address");
                        phone = myresult.getString("contact_no");

                        mymodel.addRow(new Object[]{id, name, add, phone});
                    } while (myresult.next());
                } else {
                    if (!nb.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "no records present");
                    }
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    String path = "jdbc:mysql://localhost:3306/";
    String place = "project1";


    int n = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to delete this employee record ?");
    if (n == 0) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "delete from newemployee where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, eb.getText());


                int b = mystatement.executeUpdate();
                String q1 = "delete from usertable where username=?";
                PreparedStatement mystatement1 = myconnection.prepareStatement(q1);
                mystatement1.setString(1, eb.getText());


                mystatement1.executeUpdate();

                if (b > 0) {

                    nb.setText("");
                    jButton3ActionPerformed(null);
                    JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");


                } else {
                    JOptionPane.showMessageDialog(rootPane, "Already Deleted");
                }


                mystatement.close();
                myconnection.close();
            } catch (Exception e) {
                //System.out.println("Error in query"+e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
            }
        } catch (Exception e) {
            //System.out.println("Error on connnection"+e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage());
        }

        eb.setText(null);
        nb.setText(null);
        ab.setText(null);
        cb.setText(null);
        buttonGroup1.clearSelection();
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        sb.setText(null);
    }

}//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField cb;
    private javax.swing.JTextField eb;
    private javax.swing.JRadioButton fb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton mb;
    private javax.swing.JTextField nb;
    private javax.swing.JTextField sb;
    // End of variables declaration//GEN-END:variables
}
